/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helloSol from "./hello.sol";
export type { helloSol };
export type { DigitalCollectible } from "./DigitalCollectible";
