/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as helloSol from "./hello.sol";
export { DigitalCollectible__factory } from "./DigitalCollectible__factory";
